config/routes.rb
Rails.application.routes.draw do
  resources :furniture_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "furniture_items#index"
  # get "/furniture_items", to: "articles#index" no need because I ALREADY HAVE RESOURCES


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/furniture_item.rb
class FurnitureItem < ApplicationRecord
  validates :name, presence: true
  validates :material, presence: true
  validates :image_url, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/furniture_items_controller.rb
class FurnitureItemsController < ApplicationController
  before_action :set_furniture_item, only: %i[ show edit update destroy ]

  # GET '/furniture_items', to: 'furniture_items#index'
  def index
    @furniture_items = FurnitureItem.all
  end

  # GET '/furniture_items/:id', to 'furniture_items#show'
  def show
  end

  # GET '/furniture_items/new', to: 'furniture_items#new'
  def new
    @furniture_item = FurnitureItem.new
  end

  # GET '/furniture_items/:id/edit', to: 'furniture_items#edit'
  def edit
  end

  # POST '/furniture_items', to: 'furniture_items#create'
  def create
    @furniture_item = FurnitureItem.new(furniture_item_params)

    respond_to do |format|
      if @furniture_item.save
        format.html { redirect_to furniture_item_url(@furniture_item), notice: "Furniture item was successfully created." }
        format.json { render :show, status: :created, location: @furniture_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @furniture_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT '/furniture_items/:id', to 'furniture_items#update'
  def update
    respond_to do |format|
      if @furniture_item.update(furniture_item_params)
        format.html { redirect_to furniture_item_url(@furniture_item), notice: "Furniture item was successfully updated." }
        format.json { render :show, status: :ok, location: @furniture_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @furniture_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE '/furniture_items/:id', to: 'furniture_items#destroy'
  def destroy
    @furniture_item.destroy!

    respond_to do |format|
      format.html { redirect_to furniture_items_url, notice: "Furniture item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_furniture_item
      @furniture_item = FurnitureItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def furniture_item_params
      params.require(:furniture_item).permit(:name, :material, :image_url, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furniture_items_helper.rb
module FurnitureItemsHelper
end

app/views/furniture_items/_form.html.erb
<div class= "flex items-center justify-center">
<%= form_with(model: furniture_item) do |form| %>
  <% if furniture_item.errors.any? %>
    <div style="color: red">
      <h2>You have <%= pluralize(furniture_item.errors.count, "error") %> my friend:</h2>

      <ul>
        <% furniture_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :material, style: "display: block" %>
    <%= form.text_field :material %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div class="mt-5 flex justify-center">
    <%= form.submit "Save Furniture", class: "bg-yellow-500 text-white p-2 rounded cursor-pointer transition-colors duration-300 ease-in-out hover:bg-blue-800" %>
  </div>
<% end %>
</div>

app/views/furniture_items/_furniture_item.html.erb
<div class="flex flex-col items-center justify-center font-light text-3xl mb-16" id="<%= dom_id furniture_item %>">

  <div class= "mt-1">
    <span>Name:</span>
    <%= furniture_item.name %>
  </div>

  <div class= "mt-2 mb-5">
    <span>Material:</span>
    <%= furniture_item.material %>
  </div>

  <div class= "mt-2 mb-5 pl-8 pr-5 indent-8 italic text-2xl">
    <span class="font-thin"><%= furniture_item.description %></span>
  </div>

  <div class= "mt-2 mb-5">
    <span>Price:</span>
    &#8369;<%= furniture_item.price %>
  </div>

</div>

app/views/furniture_items/edit.html.erb
<h1 class= "flex items-center justify-center font-light text-2xl mt-10 mb-10">Editing <%= @furniture_item.name %> item</h1>

<%= render "form", furniture_item: @furniture_item %>

<br>

<div class= "flex items-center justify-center mt-10">

  <%= link_to "Show this furniture item", @furniture_item, class: "bg-yellow-500 text-white p-2 rounded cursor-pointer transition-colors duration-300 ease-in-out hover:bg-blue-800 mr-1" %>
  <%= link_to "Back to furniture items", furniture_items_path, class: "bg-yellow-500 text-white p-2 rounded cursor-pointer transition-colors duration-300 ease-in-out hover:bg-blue-800 ml-1" %>
</div>

app/views/furniture_items/index.html.erb
<div class = "containers flex flex-col items-center justify-center bg-slate-300 scroll-smooth">

<p style="color: green"><%= notice %></p>

<div  class=" flex flex-col items-center justify-center bg-slate-100 w-10/12 h-auto mt-20 mb-20 scroll-smooth">
<h1 class = "text-8xl mt-14 mb-2">IDEA</h1>
<h1 class = "text-s font-light">an IKEA rip-off blog</h1>
<%= link_to "Add a furniture", new_furniture_item_path, class: "bg-yellow-400 text-white p-2 rounded cursor-pointer mt-5 mb-16 transition-colors duration-300 ease-in-out hover:bg-blue-800" %>

<div class ="flex flex-col items-center justify-center mt-2" id="furniture_items">

  <% @furniture_items.each do |furniture_item| %>
    
    <% if furniture_item.image_url.present? %>
      <%= link_to furniture_item do %>
        <%= image_tag(furniture_item.image_url, class: "w-full h-full mb-5 rounded-xl snap-start scroll-smooth") %>
      <% end %>
    <% end %>

  <div class= "mt-1 font-light text-3xl">
    <span>Name:</span>
    <%= furniture_item.name %>
  </div>

  <div class= "mt-2 mb-20 font-light text-3xl">
    <span>Material:</span>
    <%= furniture_item.material %>
  </div>

  <% end %>
</div>

</div>

</div>

app/views/furniture_items/new.html.erb
<div class= "mt-20">
<h1 class= "flex justify-center items-center text-4xl mb-10">New furniture item</h1>

<%= render "form", furniture_item: @furniture_item %>

<br>

<div class= "flex justify-center items-center">
  <%= link_to "Back to furniture items", furniture_items_path, class: "mt-10 bg-yellow-500 text-white p-2 rounded cursor-pointer transition-colors duration-300 ease-in-out hover:bg-blue-800" %>
</div>
</div>

app/views/furniture_items/show.html.erb
<div class="overflow-hidden">
  <span style="color: green"><%= notice %></span>
  <div class = "grid grid-cols-2 items-center justify-center">
    <%= image_tag(@furniture_item.image_url, class: "grid-rows-subgrid row-span-2 mt-10 mb-10 h-full w-full") if @furniture_item.image_url.present? %>
    <%= render @furniture_item %> 

    <div class = "flex items-center justify-center mb-10 overflow-hidden">
      <%= link_to "Edit #{@furniture_item.name}", edit_furniture_item_path(@furniture_item), class: "bg-yellow-500 text-white p-2 rounded cursor-pointer transition-colors duration-300 ease-in-out hover:bg-blue-800 mr-1" %>
      <%= link_to "Back to Furnitures", furniture_items_path, class: "bg-yellow-500 text-white p-2 rounded cursor-pointer transition-colors duration-300 ease-in-out hover:bg-blue-800 mr-1 ml-1" %>
      <%= link_to "Destroy #{@furniture_item.name}", @furniture_item, data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure you want to delete #{@furniture_item.name}?"
            }, class: "bg-yellow-500 text-white p-2 rounded cursor-pointer transition-colors duration-300 ease-in-out hover:bg-red-500 ml-1" %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furniture</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-stone-50">
    <main>
      <%= yield %>
    </main>
  </body>
</html>